<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AYSTravel.Web-2f6ca9e8-028a-4b28-9956-2072a9d166ae</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AYSTravel.Data\AYSTravel.Data.csproj" />
    <ProjectReference Include="..\AYSTravel.Logic\AYSTravel.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Data\" />
  </ItemGroup>

</Project>
